// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Easypay_Wrapper {
	
	
	public partial class EasypayCreatePaymentReferenceExample {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ep_box;
		
		protected System.Web.UI.WebControls.Label lblEntity;
		
		protected System.Web.UI.WebControls.Label lblReference;
		
		protected System.Web.UI.WebControls.Label lblValue;
		
		protected System.Web.UI.WebControls.Literal lUrl;
		
		protected System.Web.UI.WebControls.LinkButton lbutton1;
	}
}
